version: "3.9"
volumes:
    database:
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        container_name: db
        volumes:
            - database:/data/db
        networks:
            - my-network

networks:
    my-network:
        driver: bridge